### ISSUE TITLE
Thiếu tài liệu hướng dẫn

### ISSUE THREAD

**Issue by zukahai** [Nam077/smart-home-iot#1]
### Thiếu tài liệu hướng dẫn

**Mô tả:**
Dự án hiện tại thiếu tài liệu hướng dẫn chi tiết về cách cài đặt, cấu hình và sử dụng. Điều này có thể gây khó khăn cho người dùng mới khi muốn triển khai và sử dụng hệ thống.

**Đề xuất:**
1. Thêm tệp `README.md` với các mục sau:
   - Giới thiệu về dự án
   - Yêu cầu hệ thống
   - Hướng dẫn cài đặt
   - Hướng dẫn sử dụng
   - Liên hệ hỗ trợ

2. Cung cấp các ví dụ mẫu và tài liệu API nếu có.

**Lợi ích:**
- Giúp người dùng dễ dàng tiếp cận và sử dụng dự án.
- Tăng tính chuyên nghiệp và sự tin cậy cho dự án.

**Comment by Nam088** [comment]
oke sẽ update trong thời gian tới nhé sếp
